# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
# TODO: Add Flutter Module
flutter_application_path = '../flutter_module'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'cool-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for cool-ios

  # TODO: Add Flutter Module
  install_all_flutter_pods(flutter_application_path)

  target 'cool-iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'cool-iosUITests' do
    # Pods for testing
  end

end

# TODO: Add Flutter Module
post_install do |installer|
  flutter_post_install(installer) if defined?(flutter_post_install)
end
